spring:
  profiles: default
  application:
    name: promotion-data-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: assignment
logging:
  level:
    root: INFO
server:
  port: 8081
